### ISSUE TITLE
retrieve device_data without loading the form

### ISSUE THREAD

**Issue by EricWVGG** [nathanstitt/react-braintree-fields#11]
Does anyone know the best way to instantiate a Braintree instance for the use of retrieving the device_data, without pulling up the fields interface? (In my app, collecting payment information via Braintree hosted fields can happen at one stage, and a transaction  — which submits device_data for fraud protection — could happen at a different stage or even months later.)

**Comment by nathanstitt** [comment]
Hm, no I don't see any real way you could do that using this library directly.  It depends on `componentDidMount` which is only called when it's rendered.


I suppose you could replicate the logic I have in the `setAuthorization` method to instantiate your own DataCollector though https://github.com/nathanstitt/react-braintree-fields/blob/master/src/api.js#L29-L44
