### ISSUE TITLE
custom field wrappers

### ISSUE THREAD

**Issue by darkbercislaw** [nathanstitt/react-braintree-fields#14]
Hi,

at the moment the library assigns ids to the hosted fields placeholders internally. It starts with `field-wrapper-2` (which seems like a minor issue, as IMO logically it should start with `fields-wrapper-1`). As I want to use my own labels that relate to the fields, I set their "for" attributes to `fields-wrapper-2`, `fields-wrapper-3`, etc. These values depend on the internal implementation of the library that might change and therefore break my implementation. Would it be possible to add an optional id prop to the HostedField component (or solve it differently) so that the ids could be managed outside of the lib?

Regards,
Robert

**Comment by nathanstitt** [comment]
Hi @darkbercislaw,

I'm a bit confused by your request because currently the id values are set on a `div`, which shouldn't break their use as labels as far as I can see.  https://github.com/nathanstitt/react-braintree-fields/blob/master/src/field.jsx#L49

However, you're correct that there isn't really any reason to use `id`, we could just as easily use a `data-field-id` attribute or something like that.

**Comment by darkbercislaw** [comment]
@nathanstitt maybe I wasn't clear.

Setting the ids on the hosted fields placeholders (divs) lets us match these divs with the labels - therefore clicking on a label brings focus onto the HostedField input (at least that's the way it works in my case). That is the desired behavior. 

The problem is that the ids are managed internally and if someday, in a future version of the lib, you decide to change 'field-wrapper-x' to something else, clicking on the label will no longer focus a related input field. There is also a potential issue that you mentioned - duplication of the ids on a webpage if someone unknowingly decides to use the same ids. Therefore, IMO it would be beneficial to allow setting the fields` ids via the HosteField component props.

**Comment by nathanstitt** [comment]
Hey @darkbercislaw, I think you were clear, I was just obtuse 😁 

I now understand what you're saying and agree that it makes sense to do so, I'll make that change in the next week or so.

However, the way I've always handled focus is to obtain the field reference, then call `focus()` or `blur()` methods on it.  You can see an example of that in the demo, obtaining the ref: https://github.com/nathanstitt/react-braintree-fields/blob/master/demo.jsx#L105  and then
focusing https://github.com/nathanstitt/react-braintree-fields/blob/master/demo.jsx#L70 

BTW, it's also not a great idea to assume the generated id values will be stable, if the component unmounts/mounts, the id's will increment to always be unique. https://github.com/nathanstitt/react-braintree-fields/blob/master/src/api.js#L48-L51  the code there also explains why it starts at 2, the value is initialized at 1, but it adds 1 before returning it.
