### ISSUE TITLE
Release version to include support for rejectUnsupportedCards

### ISSUE THREAD

**Issue by leschaller1** [nathanstitt/react-braintree-fields#16]
Could you release a version that includes support for rejectUnsupportedCards? 
This is the commit I'm referring to: https://github.com/nathanstitt/react-braintree-fields/commit/595c8b24ccca6f3e4162a70c690536c160daaa76

**Comment by nathanstitt** [comment]
I've released version 1.2 that has the support, thanks for your patience!
