### ISSUE TITLE
Add onAuthorizationSuccess callback

### ISSUE THREAD

**Issue by brendanlacroix** [nathanstitt/react-braintree-fields#2]
Hey hey, love the project!

Braintree forms take a sec to initialize, so I was thinking you could add an `onAuthorizationSuccess` callback to the `Braintree` component to toggle a loading/disabled state.

Here's what I'm thinking: https://github.com/brendanlacroix/react-braintree-fields/compare/master...brendanlacroix:add-onAuthorizationSuccess-callback

If you're amenable, I can finish up my branch with tests + docs and submit a PR 👍

**Comment by nathanstitt** [comment]
Thanks @brendanlacroix!

Yes that's a great idea.  Please do submit that as a PR, I'd love to include it.
