### ISSUE TITLE
How to add loader when hosted field while authentication process in ongoing

### ISSUE THREAD

**Issue by meetpatel-bacancy** [nathanstitt/react-braintree-fields#22]

**Comment by nathanstitt** [comment]
@meetpatel-bacancy I'm afraid I don't understand what you're asking.  What is the  "loader?" you're referring to, and we don't use any authentication.

Can you provide a code sample of what you're attempting?

**Comment by meetpatel-bacancy** [comment]
I want to hide hosted feild until authentication is not completed/ show loader instead of empty hosted fields

**Comment by nathanstitt** [comment]
I see.  There's several ways you could do that, perhaps the simplest would be to create a wrapper component and not render them, something like:

```
const MyBrraintreeWrapper = (user) => {
   if (!user.isLoggedIn) return null;
   return (
    <Braintree> .... </Braintree>
  )
}
```

Or you could wrap it in a div and set that to `display:none` if you do wan't to render but hide them.

Regardless I'm afraid this is a bit out of the scope of what this library will accomplish.  I hope these suggestions help you.
