### ISSUE TITLE
Problem with then getToken() function

### ISSUE THREAD

**Issue by NiklasCODES** [nathanstitt/react-braintree-fields#23]
Hey :) My name is Niklas, I have tried out your cool lib, but I got stuck on one point. When I try to call the getToken() function in the onSubmit() function like in your example, I get an error message saying that getToken() is undefined. I am not good a working with refs so I guess I screwed up something.
This is my code: 
`import React from "react";
import axios from "axios";
import { Braintree, HostedField } from "react-braintree-fields";

export class BuyButton extends React.PureComponent {
    instance;

    constructor(props) {
        super(props);
        this.state = {
            clientToken: null,
            paid: false,
            card: null,
            isBraintreeReady: false
        }
    }

    componentDidMount() {
         //getting client token and calling setState({ clientToken: "xyz"})
    }

    onSubmit() {
        //this is where the error is
        this.getToken({ cardholderName: "My Order Name"}).then((payload) => {
            console.log("Nonce: " + payload.nonce);
            console.log("Device data: " + this.deviceData);
        });

       
    }

    onFocus( event) {
        console.log("number is focused", event)
    }

    onError(err) {
        console.warn(err);
        this.ccNum.focus();
    }

    onAuthorizationSuccess() {
        this.setState({ isBraintreeReady: true});
    }

    onDataCollectorInstanceReady( err, dataCollectorInstance) {
        if(!err) this.device_data = dataCollectorInstance.deviceData;
    }

    render() {
        
        if(!this.state.clientToken) {
            return (
                <div>
                    <h1>Loading...</h1>
                </div>
            );
        } else if(this.props.amount == null) {
            return(<div>Amount not defined!</div>)
        } else {
            return(
                <Braintree
                    className={ this.state.isBraintreeReady ? '' : 'disabled' }
                    authorization={this.state.clientToken}
                    onAuthorizationSuccess={this.onAuthorizationSuccess}
                    onDataCollectorInstanceReady={this.onDataCollectorInstanceReady}
                    onError={this.handleError}
                    onCardTypeChange={this.onCardTypeChange}
                    getTokenRef={ref => (this.getToken = ref)}
                    styles={{
                        'input': {
                            'font-size': '1rem',
                            'color': '#4795057'
                        },
                        ':focus': {
                            'color': 'black'
                        }
                    }}
                >
                    <div className="fields">
                        <div className="form-group">
                            <label>Credit Card Number</label>
                            <HostedField className="form-control" type="number" onFocus={this.onFocus} ref={ccNum => (this.ccNum = ccNum)} />
                        </div>
                        <div className="form-group">
                            <label>Expiration Date</label>
                            <HostedField className="form-control" type="expirationDate" />
                        </div>
                        <div className="form-group">
                            <label>CVV</label>
                            <HostedField className="form-control" type="cvv" />
                        </div>
                        <br />
                        <button className="btn btn-primary" style={{ width: "100%"}} onClick={this.onSubmit}>Submit</button>
                    </div>
                </Braintree>
            );
        }
    }
}`

Error Message: TypeError: Cannot read property 'getToken' of undefined

>

**Comment by NiklasCODES** [comment]
I just forgot to include the initialization stuff and importing your lib 
for example:

`class MyComponent extends React.PureComponent`

**Comment by nathanstitt** [comment]
Hi @NiklasCODES it looks to me like you're not binding the `onSubmit` to the class, so it's calling as a plain function.  Try changing `onSubmit` to something like:

```js
onSubmit = () => {
    this.getToken({ cardholderName: "My Order Name"}).then((payload) => {
        console.log("Nonce: " + payload.nonce);
        console.log("Device data: " + this.deviceData);
    });
}
```

If you're more familiar with function based react, I've also got an example of that here: https://github.com/nathanstitt/react-braintree-fields/blob/master/demo/demo-functional.jsx

**Comment by NiklasCODES** [comment]
Lovely, for your fast solution! Thank you very much for your help!
