### ISSUE TITLE
Use new context API

### ISSUE THREAD

**Issue by andrewtremblay** [nathanstitt/react-braintree-fields#27]
This repo appears to use getChildContext and childContextTypes, which is the legacy context implementation. 

https://github.com/nathanstitt/react-braintree-fields/blob/20a7e06711a6107da2ed019612871233ec59139c/src/braintree.jsx#L24

https://github.com/nathanstitt/react-braintree-fields/blob/20a7e06711a6107da2ed019612871233ec59139c/src/braintree.jsx#L52

>The legacy context API will be removed in a future major version. Use the new context API introduced with version 16.3. The legacy API will continue working for all 16.x releases.

https://reactjs.org/docs/legacy-context.html

In order for this library to be compatible with future versions of React, the new context API should be used instead.  
https://reactjs.org/docs/context.html

**Comment by nathanstitt** [comment]
@andrewtremblay 

We haven't upgraded the use of context api yet so we could continue to support React 15.  However it's probably been long enough that we could upgrade at this point. 

PR's to do so are welcome

**Comment by lewiscarvillesputnik** [comment]
Are there any plans to upgrade this to use the latest context api? Our project's currently on react 17, and while it appears to work as intended it is slgihtly concerning.

**Comment by nathanstitt** [comment]
@lewiscarvillesputnik yes it'll be updated at some point. it's in production use at my "real job" but we're still on 17 so haven't yet needed to upgrade.  In theory it should be pretty easy to update, I've done a few other context upgrades without issues.

**Comment by dan003400** [comment]
Any update on this? We are seeing console warning for legacy context api usage.

**Comment by cloudworkpro-dave** [comment]
Any update on this? Also seeing console warnings
