### ISSUE TITLE
The rendered form is not accessible

### ISSUE THREAD

**Issue by mhchen** [nathanstitt/react-braintree-fields#30]
Note that in the demo, clicking on the labels does not highlight the corresponding fields. Screen readers will struggle with this as well. I believe the main issue is that the input ids are auto-generated, and we can't provide ones that map to the `htmlFor` of the labels we're using outside of the iframe. Would you be open to a PR that adds `id` as a prop to `HostedField`?

**Comment by nathanstitt** [comment]
thanks for raising this @mhchen - unfortunately I think this is a side effect of the way Braintree renders the form inputs inside the iframe.  I'd be very open to a PR to correct it if you see a way to do so, but it's not clear to me how we'd accomplish it.

**Comment by nathanstitt** [comment]
Closing since we haven't came up with a solution
