### ISSUE TITLE
Hide cvv

### ISSUE THREAD

**Issue by gowgow1** [nathanstitt/react-braintree-fields#37]
Hi,
I'm writting you to say that we haven't any way to hide cvv and add some inputMask .
like that has default braintree fields.
![image](https://user-images.githubusercontent.com/47568275/154316053-e3d3811c-58ba-46f6-ac1a-c160f798d855.png)
could you provide me some information how to do it.
thank you for future.

**Comment by nathanstitt** [comment]
Hi @gowgow1 to hide the CVV you could just not render the field.  As for the maskInput option, I just added a new `options` property and an example of using it here: https://github.com/nathanstitt/react-braintree-fields/blob/main/demo/demo-class.jsx#L112

This is released as version `1.8.0`

Hope this works well for you

**Comment by gowgow1** [comment]
thanks a lot, that suits for our needs, great job!
