### ISSUE TITLE
Get device_data

### ISSUE THREAD

**Issue by mattiaocchiuto** [nathanstitt/react-braintree-fields#5]
Hi, in order to collect the [device_data](https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v3) from the current Braintree client instance, I'd like to know if there is a way to have a reference of the instantiated client.
[Looking at the source code](https://github.com/nathanstitt/react-braintree-fields/blob/c90f3f9c4c40377fcfecaddebb4fa2126bd10315/src/api.js#L22) seems to me that there is no way actually, do I'm missing something?

Thanks for your help!

**Comment by mattiaocchiuto** [comment]
I've opened this PR that should add this capability https://github.com/nathanstitt/react-braintree-fields/pull/6

**Comment by nathanstitt** [comment]
Thanks @mattiaocchiuto!  I've just released version `0.10.0` (I messed up 0.9 by not pulling before creating the tag 😊 )
