### ISSUE TITLE
How to set expiration year dropdown values to 2-digit values?

### ISSUE THREAD

**Issue by draganavivify** [nathanstitt/react-braintree-fields#61]
Hi, I need to get 22, 23, 24 instead of 2022, 2023, 2024, etc. in the dropdown for the expiration year field.

I managed to do that for the expiration month (01, instead of 1), with the select options parameter, that I found in the documentation, where I use my own array of values. This can only be used for the expiration month field, according to documentation. So for the expiration year that doesn't work, and I haven't seen some other options. Any suggestions?

**Comment by nathanstitt** [comment]
Hi @draganavivify I'm sorry but I don't see how to do that with the Braintree api as it's documented.  if you do manage to get it working using their api I'd be interested in seeing an example so I could do so as well
